In [1]:
import pandas as pd

In [2]:
test = pd.read_csv('data/syn_flood_ddos_flows.csv')

In [3]:
print(test.columns.to_list())

['src_ip', 'dst_ip', 'src_port', 'dst_port', 'protocol', 'timestamp', 'flow_duration', 'flow_byts_s', 'flow_pkts_s', 'fwd_pkts_s', 'bwd_pkts_s', 'tot_fwd_pkts', 'tot_bwd_pkts', 'totlen_fwd_pkts', 'totlen_bwd_pkts', 'fwd_pkt_len_max', 'fwd_pkt_len_min', 'fwd_pkt_len_mean', 'fwd_pkt_len_std', 'bwd_pkt_len_max', 'bwd_pkt_len_min', 'bwd_pkt_len_mean', 'bwd_pkt_len_std', 'pkt_len_max', 'pkt_len_min', 'pkt_len_mean', 'pkt_len_std', 'pkt_len_var', 'fwd_header_len', 'bwd_header_len', 'fwd_seg_size_min', 'fwd_act_data_pkts', 'flow_iat_mean', 'flow_iat_max', 'flow_iat_min', 'flow_iat_std', 'fwd_iat_tot', 'fwd_iat_max', 'fwd_iat_min', 'fwd_iat_mean', 'fwd_iat_std', 'bwd_iat_tot', 'bwd_iat_max', 'bwd_iat_min', 'bwd_iat_mean', 'bwd_iat_std', 'fwd_psh_flags', 'bwd_psh_flags', 'fwd_urg_flags', 'bwd_urg_flags', 'fin_flag_cnt', 'syn_flag_cnt', 'rst_flag_cnt', 'psh_flag_cnt', 'ack_flag_cnt', 'urg_flag_cnt', 'ece_flag_cnt', 'down_up_ratio', 'pkt_size_avg', 'init_fwd_win_byts', 'init_bwd_win_byts', 'active_max', 'active_min', 'active_mean', 'active_std', 'idle_max', 'idle_min', 'idle_mean', 'idle_std', 'fwd_byts_b_avg', 'fwd_pkts_b_avg', 'bwd_byts_b_avg', 'bwd_pkts_b_avg', 'fwd_blk_rate_avg', 'bwd_blk_rate_avg', 'fwd_seg_size_avg', 'bwd_seg_size_avg', 'cwr_flag_count', 'subflow_fwd_pkts', 'subflow_bwd_pkts', 'subflow_fwd_byts', 'subflow_bwd_byts']

In [4]:
test.head()

,src_ip,dst_ip,src_port,dst_port,protocol,timestamp,flow_duration,flow_byts_s,flow_pkts_s,fwd_pkts_s,...,bwd_pkts_b_avg,fwd_blk_rate_avg,bwd_blk_rate_avg,fwd_seg_size_avg,bwd_seg_size_avg,cwr_flag_count,subflow_fwd_pkts,subflow_bwd_pkts,subflow_fwd_byts,subflow_bwd_byts
0,127.0.0.1,172.17.254.114,26027,8001,6,2025-06-22 15:20:54,91.507007,1.967062,0.032784,0.032784,...,0,0,0,60.0,0,0,3,0,180,0
1,127.0.0.1,172.17.254.114,11728,8001,6,2025-06-22 15:20:50,100.574597,1.789716,0.029829,0.029829,...,0,0,0,60.0,0,0,3,0,180,0
2,127.0.0.1,172.17.254.114,9332,8001,6,2025-06-22 15:20:57,95.494245,1.884930,0.031416,0.031416,...,0,0,0,60.0,0,0,3,0,180,0
3,127.0.0.1,172.17.254.114,12346,8001,6,2025-06-22 15:20:59,95.096946,1.892805,0.031547,0.031547,...,0,0,0,60.0,0,0,3,0,180,0
4,127.0.0.1,172.17.254.114,51492,8001,6,2025-06-22 15:20:59,95.146911,1.891811,0.031530,0.031530,...,0,0,0,60.0,0,0,3,0,180,0

In [5]:
benign = pd.read_csv('data/ddos_suite2_benign_flows.csv')

In [6]:
benign.head()

,src_ip,dst_ip,src_port,dst_port,protocol,timestamp,flow_duration,flow_byts_s,flow_pkts_s,fwd_pkts_s,...,bwd_pkts_b_avg,fwd_blk_rate_avg,bwd_blk_rate_avg,fwd_seg_size_avg,bwd_seg_size_avg,cwr_flag_count,subflow_fwd_pkts,subflow_bwd_pkts,subflow_fwd_byts,subflow_bwd_byts
0,172.17.4.11,69.173.158.92,43092,443,6,2025-06-22 16:43:53,90.257108,5.118710,0.077556,0.044318,...,0.000000,0.000000,0.000000e+00,66.000000,66.000000,0,4,3,264,198
1,172.17.4.11,117.251.120.76,53788,443,17,2025-06-22 16:43:59,90.023908,629151.025081,553.675141,70.025842,...,8.513142,0.000000,1.057015e+07,80.204791,1289.228824,0,6304,43540,505611,56133023
2,172.17.4.11,203.195.121.141,54948,443,6,2025-06-22 16:44:02,90.224470,5.120562,0.077584,0.044334,...,0.000000,0.000000,0.000000e+00,66.000000,66.000000,0,4,3,264,198
3,172.17.4.11,216.58.196.110,58515,443,17,2025-06-22 16:44:01,93.122698,192.810135,0.730219,0.332894,...,0.000000,0.000000,0.000000e+00,479.225806,83.756757,0,31,37,14856,3099
4,216.58.200.206,172.17.4.11,443,49413,17,2025-06-22 16:43:54,100.264315,169.202772,0.598418,0.359051,...,0.000000,54374.031069,0.000000e+00,364.194444,160.583333,0,36,24,13111,3854

In [1]:
import pandas as pd
import os

# Top 15 features for training
selected_columns = [
    'flow_duration', 'flow_byts_s', 'flow_pkts_s',
    'tot_fwd_pkts', 'tot_bwd_pkts',
    'fwd_pkt_len_mean', 'bwd_pkt_len_mean',
    'pkt_len_var',
    'flow_iat_mean', 'fwd_iat_max', 'bwd_iat_max',
    'pkt_size_avg',
    'syn_flag_cnt', 'ack_flag_cnt',
    'init_fwd_win_byts'
]

# Filepath + labels
data_files = {
    "ddos_suite2_benign_flows.csv": "BENIGN",
    "benign_ddos_suite1_flows.csv": "BENIGN",
    "syn_flood_ddos_flows.csv": "SYN_FLOOD",
    "synonymous_ip_ddos_flows.csv": "IP_SPOOF",
    "tcp_flood_ddos_flows.csv": "TCP_FLOOD",
    "udp_flood_ddos_flows.csv": "UDP_FLOOD",
    "ACK_floods_flows.csv": "ACK_FLOOD",
    "ddos_syn_ack_flows.csv": "SYN_ACK",
    "ddos_udp_frag_flows.csv": "UDP_FRAG",
    "ddos_udpplain.csv": "UDP_PLAIN",
}

# Directory path (change as per Kaggle / Colab mount if needed)
data_dir = "data/"  # Update if needed
combined_df = pd.DataFrame()

# Loop through files and combine
for file, label in data_files.items():
    path = os.path.join(data_dir, file)
    
    # Read only selected cols + first 100k rows
    df = pd.read_csv(path, usecols=selected_columns, nrows=100000)
    df["target"] = label  # add label
    combined_df = pd.concat([combined_df, df], ignore_index=True)

# Save combined output
combined_df.to_csv("gpin_data.csv", index=False)
print("✅ Combined dataset created with shape:", combined_df.shape)

✅ Combined dataset created with shape: (941783, 16)

In [2]:
combined_df.head()

,flow_duration,flow_byts_s,flow_pkts_s,tot_fwd_pkts,tot_bwd_pkts,fwd_pkt_len_mean,bwd_pkt_len_mean,pkt_len_var,flow_iat_mean,fwd_iat_max,bwd_iat_max,syn_flag_cnt,ack_flag_cnt,pkt_size_avg,init_fwd_win_byts,target
0,90.257108,5.118710,0.077556,4,3,66.000000,66.000000,0.000000,15.042851,45.079989,45.113542,0,7,66.000000,646,BENIGN
1,90.023908,629151.025081,553.675141,6304,43540,80.204791,1289.228824,164144.816865,0.001806,13.660580,13.667071,0,0,1136.317992,0,BENIGN
2,90.224470,5.120562,0.077584,4,3,66.000000,66.000000,0.000000,15.037412,45.075017,45.075194,0,7,66.000000,626,BENIGN
3,93.122698,192.810135,0.730219,31,37,479.225806,83.756757,161777.953936,1.389891,20.829559,20.828731,0,0,264.044118,0,BENIGN
4,100.264315,169.202772,0.598418,36,24,364.194444,160.583333,158646.020833,1.699395,15.020735,14.997148,0,0,282.750000,0,BENIGN

In [3]:
combined_df[100001:].head()

,flow_duration,flow_byts_s,flow_pkts_s,tot_fwd_pkts,tot_bwd_pkts,fwd_pkt_len_mean,bwd_pkt_len_mean,pkt_len_var,flow_iat_mean,fwd_iat_max,bwd_iat_max,syn_flag_cnt,ack_flag_cnt,pkt_size_avg,init_fwd_win_byts,target
100001,90.014153,382.084360,2.033014,183,0,187.939891,0.000000,10505.936278,0.494583,1.000328,0.000000,0,0,187.939891,0,BENIGN
100002,90.040285,45.579598,0.133274,12,0,342.000000,0.000000,0.000000,8.185480,23.009800,0.000000,0,0,342.000000,0,BENIGN
100003,92.277884,3765.279230,5.981932,222,330,578.085586,663.990909,332844.543741,0.167473,20.894360,20.895159,0,0,629.442029,0,BENIGN
100004,93.640727,936234.145213,807.629356,7675,67952,82.435831,1280.859298,139612.511737,0.001238,14.398486,14.403228,0,0,1159.237389,0,BENIGN
100005,92.194284,27.919301,0.423020,20,19,66.000000,66.000000,0.000000,2.426165,10.107038,10.141358,0,39,66.000000,544,BENIGN

In [4]:
combined_df[200001:].head()

,flow_duration,flow_byts_s,flow_pkts_s,tot_fwd_pkts,tot_bwd_pkts,fwd_pkt_len_mean,bwd_pkt_len_mean,pkt_len_var,flow_iat_mean,fwd_iat_max,bwd_iat_max,syn_flag_cnt,ack_flag_cnt,pkt_size_avg,init_fwd_win_byts,target
200001,100.574597,1.789716,0.029829,3,0,60.0,0.0,0.0,50.287298,100.574597,0.0,3,0,60.0,8192,SYN_FLOOD
200002,95.494245,1.884930,0.031416,3,0,60.0,0.0,0.0,47.747123,95.494245,0.0,3,0,60.0,8192,SYN_FLOOD
200003,95.096946,1.892805,0.031547,3,0,60.0,0.0,0.0,47.548473,95.096946,0.0,3,0,60.0,8192,SYN_FLOOD
200004,95.146911,1.891811,0.031530,3,0,60.0,0.0,0.0,47.573456,95.146911,0.0,3,0,60.0,8192,SYN_FLOOD
200005,105.352283,1.708553,0.028476,3,0,60.0,0.0,0.0,52.676141,105.352283,0.0,3,0,60.0,8192,SYN_FLOOD

In [11]:
combined_df[300001:].head()

,flow_duration,flow_byts_s,flow_pkts_s,tot_fwd_pkts,tot_bwd_pkts,fwd_pkt_len_mean,bwd_pkt_len_mean,pkt_len_var,flow_iat_mean,fwd_iat_max,bwd_iat_max,syn_flag_cnt,ack_flag_cnt,pkt_size_avg,init_fwd_win_byts,target
300001,93.787809,3.699841,0.031987,3,0,115.666667,0.0,80.222222,46.893904,93.787809,0.0,0,2,115.666667,8192,TCP_FLOOD
300002,103.638088,2.913987,0.028947,3,0,100.666667,0.0,0.222222,51.819044,103.638088,0.0,0,1,100.666667,8192,TCP_FLOOD
300003,99.868424,2.733597,0.030040,3,0,91.000000,0.0,18.000000,49.934212,99.868424,0.0,1,1,91.000000,8192,TCP_FLOOD
300004,101.152728,4.488263,0.029658,3,0,151.333333,0.0,10.888889,50.576364,101.152728,0.0,0,0,151.333333,8192,TCP_FLOOD
300005,106.797794,3.108678,0.028090,3,0,110.666667,0.0,0.222222,53.398897,106.797794,0.0,0,1,110.666667,8192,TCP_FLOOD

In [5]:
combined_df[400001:].head()

,flow_duration,flow_byts_s,flow_pkts_s,tot_fwd_pkts,tot_bwd_pkts,fwd_pkt_len_mean,bwd_pkt_len_mean,pkt_len_var,flow_iat_mean,fwd_iat_max,bwd_iat_max,syn_flag_cnt,ack_flag_cnt,pkt_size_avg,init_fwd_win_byts,target
400001,93.787809,3.699841,0.031987,3,0,115.666667,0.0,80.222222,46.893904,93.787809,0.0,0,2,115.666667,8192,TCP_FLOOD
400002,103.638088,2.913987,0.028947,3,0,100.666667,0.0,0.222222,51.819044,103.638088,0.0,0,1,100.666667,8192,TCP_FLOOD
400003,99.868424,2.733597,0.030040,3,0,91.000000,0.0,18.000000,49.934212,99.868424,0.0,1,1,91.000000,8192,TCP_FLOOD
400004,101.152728,4.488263,0.029658,3,0,151.333333,0.0,10.888889,50.576364,101.152728,0.0,0,0,151.333333,8192,TCP_FLOOD
400005,106.797794,3.108678,0.028090,3,0,110.666667,0.0,0.222222,53.398897,106.797794,0.0,0,1,110.666667,8192,TCP_FLOOD